Birthday1= input("John enter your birthday: ")
Birthday2= input("Sam enter your birthday: ")
Birthday3= input("Max enter your birthday: ")
Birthday4= input("Tom enter your birthday: ")
Birthday5= input("Ayaan enter your birthday: ")
print("\n John",Birthday1)
print("\n Sam", Birthday2)
print("\n Max", Birthday3)
print("\n Tom",Birthday4)
print("\n Ayaan",Birthday5)